#!/usr/bin/env python3

import sys
import traceback

class error:
    def check():
        if  len (sys.argv) == 2:
            if sys.argv[1] == "-h":
                error.help()
                return 0
        if len(sys.argv) != 3:
            raise Exception("Error: invalid number of arguments")

    def help():
        print("USAGE")
        print("\t./202unsold a b")
        print("DESCRIPTION")
        print("\ta\tconstant computed from the past results")
        print("\tb\tconstant computed from the past results")

    def debug(e):
        print(e, file=sys.stderr) # print the error
        traceback.print_exc() # where it broke

